name: CI/CD Pipeline for Tic-Tac-Toe

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'kubernetes/deployment.yml'  # Ignore changes to this file to prevent loops
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for git operations

    # Step 2: Set up Node.js to build the React project
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use the Node.js version compatible with your project

    # Step 3: Install dependencies and build the React app
    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    # Step 5: Build and push Docker image
    - name: Build and Push Docker Image
      id: docker-build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: manish181623/tic-tac-toe:${{ github.sha }} # Use Git commit hash as the image tag

    # Step 6: Update deployment.yml with the new image tag
    - name: Update Kubernetes Deployment
      run: |
        # Define the new image with tag
        NEW_IMAGE="manish181623/tic-tac-toe:${{ github.sha }}"
        
        # Update the deployment file
        sed -i "s|image: manish181623/tic-tac-toe:.*|image: ${NEW_IMAGE}|g" kubernetes/deployment.yml
        
        # Verify the change
        echo "Updated deployment to use image: ${NEW_IMAGE}"
        grep "image:" kubernetes/deployment.yml

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add kubernetes/deployment.yml
        git commit -m "Update deployment image to ${{ github.sha }} [skip ci]" || echo "No changes to commit"
        git push origin master 
