name: CI/CD Pipeline for Tic-Tac-Toe

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'kubernetes/deployment.yml'  # Ignore changes to this file to prevent loops
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Set up Node.js to build the React project
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use the Node.js version compatible with your project

    # Step 3: Install dependencies and build the React app
    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    # Step 5: Build and push Docker image
    - name: Build and Push Docker Image
      id: docker-build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: manish181623/tic-tac-toe:${{ github.sha }} # Use Git commit hash as the image tag

    # Step 6: Update deployment.yml with the new image tag
    - name: Update Deployment File
      run: |
        # Change directory to kubernetes to verify the file exists
        cd kubernetes
        ls
        cd ..
        
        # Update the image tag in the deployment file
        sed -i "s|manish181623/tic-tac-toe:.*|manish181623/tic-tac-toe:${{ github.sha }}|" kubernetes/deployment.yml
        
        # Configure git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Add the correct file path
        git add kubernetes/deployment.yml
        
        # Commit and push
        git commit -m "Update deployment.yml with new image tag: ${{ github.sha }}"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
